### ISSUE TITLE
Tracking issue for improving OSTD scheduling subsystem

### ISSUE THREAD

**Issue by jellllly420** [asterinas/asterinas#1036]
### Description

This issue tracks planned improvements of OSTD scheduling subsystem.

### Current Status

- [ ] Overhaul scheduling API 
#990 
- [ ] Move scheduler-specific information outside OSTD
- [ ] Implement missing system calls for scheduling subsystem
- [ ] Support multi-schedulers (Linux scheduling class)
- [ ] Add advanced schedulers (Linux RT (RR/FIFO), Linux CFS)
