### ISSUE TITLE
Tracking issue for supporting iperf3

### ISSUE THREAD

**Issue by lrh2000** [asterinas/asterinas#1086]
### Description

[iperf3](https://github.com/esnet/iperf) should be added as a benchmark to measure our network performance.

Steps to run:
```sh
/benchmark/bin/iperf3 -B 127.0.0.1 -s &
/benchmark/bin/iperf3 -c 127.0.0.1
```

### Current Status

 - [x] Add virtio-net benchmark
   - Done in https://github.com/asterinas/asterinas/pull/1331
 - (Canceled) Add loopback benchmark
   - Previously planned to be done in https://github.com/asterinas/asterinas/pull/1224

Blocked by:
 - [x] https://github.com/asterinas/asterinas/issues/866 (looks like it was closed by mistakes?)
   - Fixed by https://github.com/asterinas/asterinas/pull/1202
 - [x] https://github.com/asterinas/asterinas/issues/819
   - Fixed by https://github.com/asterinas/asterinas/pull/1098
 - [x] Fix unexpected page faults when accessing [this file-backed memory mapped region](https://github.com/esnet/iperf/blob/922820e446f29077adacd751adfa87c3059b7c83/src/iperf_api.c#L4446)
   - Fixed by https://github.com/asterinas/asterinas/pull/1346

### Additional Information 

In order to have a reasonable performance result, we need to:
 - [x] Bump smoltcp to include https://github.com/smoltcp-rs/smoltcp/pull/935, which fixes https://github.com/asterinas/asterinas/issues/485.
   - Done in: https://github.com/asterinas/asterinas/pull/1198

**Comment by lrh2000** [comment]
https://github.com/asterinas/asterinas/pull/1224 is closed. I assume the plan to add that benchmark has been canceled.

There is nothing left in this tracking issue. So I'm closing this as complete.
