### ISSUE TITLE
Tracking issue: Elf解析与构建地址空间

### ISSUE THREAD

**Issue by StevenJiang1110** [asterinas/asterinas#13]
目前仅支持对于非常简单的elf进行解析与构建地址空间，为了运行更加复杂的程序，需要进一步完善目前的实现。这个issue用来追踪待完善的功能。

- [x] process initial stack & register state  
  - [x] 实现initial stack的数据布局（命令行参数，环境变量等）
  - [x] 正确设置寄存器的状态(argc等)
  - [x] 用户堆空间的分配
- [x] elf解析的优化
  - [x] 允许segment的起始地址并不是page-aligned（兼容x64 ABI要求）
  - [x] 读取elf的第一个chunk（128bytes）来解析文件格式（参考Linux内部实现），而不需要读取整个elf文件的内容  
- [x] 动态链接的支持  
- [x] 用户态运行库对接内核的实现（兼容libc的实现）
