### ISSUE TITLE
Boot in the Linux way

### ISSUE THREAD

**Issue by tatetian** [asterinas/asterinas#231]
# Background and Motivation

The first three pieces of software that gets running after one presses the power button of a machine are
* Firmware (e.g., BIOS, UEFI);
* Bootloader (e.g., GRUB, Limine);
* OS kernel (e.g., Linux, OpenBSD, Windows).

Ideally, a bootloader should be able to load different types of OS kernels. This is called [multi-booting](https://en.wikipedia.org/wiki/Multi-booting). And the reversed direction is also desired: an OS kernel should also be able to get booted by different bootloaders. These two goals mean that the bootloaders and the kernels must agree upon an interface or protocol to interact with one another.

Currently, Jinux chooses to use the Limine boot protocol. And since the only bootloader that implements the protocol is Limine itself, Jinux is not compatible with any other bootloader.

The problem is that we do need to support in the near future a second bootloader, which is [tdshim](https://github.com/confidential-containers/td-shim). Tdshim is a light-weight virtual firmware for Intel TDX VM that enables starting up confidential containers with lower latencies. It also acts as a bootloader. Tdshim only supports loading Linux kernels as well as ELF files.

As every open-source bootloader, including td-shim, supports booting Linux, I think it is a smart move for us to adopt the Linux boot protocol. This way, every bootloader that works with Linux can do with Jinux.

# TODOs

- [ ] Adopt the [Linux boot protocol](https://www.kernel.org/doc/Documentation/x86/boot.txt). For regular VMs, we can choose GRUB, which also supports the Linux boot procotol. For TDX VMs, we use tdshim.
- [ ] Support the self-decompression format of [vmlinuz/zImage](https://en.wikipedia.org/wiki/Vmlinux) to reduce the kernel image size. Tdshim is limited in the sizes of kernel images that can be loaded. So compression is a must.
- [ ] Parse kernel command-line arguments passed from bootloaders. Support of CLI arguments gives us the flexibility to alter the behavior of Jinux without re-compiling.

# Learning resources

* [Hands-on Booting: Learn the Boot Process of Linux, Windows, and Unix](https://www.amazon.com/Hands-Booting-Learn-Process-Windows/dp/1484258894). This books provide a good overview of the boot process of machine, including how the firmware, the bootloader, and the kernel interacts with each other.
* [Linux Insides](https://0xax.gitbooks.io/linux-insides/content/Booting/). This tutorial describes how Linux kernel boots.
