### ISSUE TITLE
Tracking issue for supporting dropbear server and client

### ISSUE THREAD

**Issue by StevenJiang1110** [asterinas/asterinas#245]
[Dropbear](https://matt.ucc.asn.au/dropbear/dropbear.html) is a rather small ssh server and client. It can be compiled statically and its size is only about hundreds of KBs. It is a suitable target to demo ssh for jinux at this time.

To support dropbear client & server ( learn from strace, not all is essential ) :
- network
  - [ ] support bind/connect/listen at 0.0.0.0
  - [x] support nonblocking IP socket
  - sockopt:
    - [ ] SOL_SOCKET: SO_REUSEADDR, SO_LINGER
    - [ ] SOL_TCP: TCP_NODELAY, TCP_FASTOPEN
    - [ ] SOL_IP: IP_TOS
    - [ ] SOL_IPV6: IPV6_V6ONLY, IPV6_TCLASS
- procfs entrypoints: 
  - [ ] /proc/loadavg
  - [ ] /proc/interrupts
  - [ ] /proc/loadavg
  - [ ] /proc/sys/kernel/random/entropy_avail
  - [ ] /proc/net/netstat
  - [ ] /proc/net/dev
  - [ ] /proc/net/tcp
  - [ ] /proc/net/rt_cache
  - [ ] /proc/vmstat
- devfs entrypoints
  - [x] /dev/urandom
  - [x] #214 
- missing syscalls:
  - [x] getsockopt
  - [ ] setsid
  - [x] execveat
  - [ ] setgroups
  - [ ] sysinfo
  - [ ] getgroups
  - [ ] faccessat
  - [ ] fchmod
  - [ ] chown
  - [ ] pselect6
  - [x] getrandom
  - [ ] clock_gettime supports CLOCK_PROCESS_CPUTIME_ID
