### ISSUE TITLE
Tracking the unimplemented syscall to support busybox ash

### ISSUE THREAD

**Issue by StevenJiang1110** [asterinas/asterinas#36]
This issue tracks the essential syscall to support busybox binaries. We compile a statically linked busybox(other configs are as default), then use strace to record the syscall.

The unimplemented syscalls for running `ash`:
- [ ] readlink (only can read /proc/self/exe, returns the name of current executable file)
- [ ] mprotect (only a fake implementation now)
- [x] prctl (Set or get process name)
- [x] getppid
- [ ] getcwd (only return the root directory as a fake result now)
- [ ] ioctl (support commands about termios)
- [ ] fcntl (only support a naive dup now)
- [x] getpgrp
- [x] rt_sigaction
- [x] setpgid
- [ ] openat (only return ENOENT now)
- [ ] fstat (only return fake result for stdout now)
- [x] read 
- [x] close
- [ ] geteuid (only return fake result now)
- [ ] write (only write to stdout now)
- [x] poll

Syscalls to implement for running `ls` in `ash`:
- [ ] lseek
- [ ] vfork
