### ISSUE TITLE
Tracking todo list in 11.11 weekly meeting

### ISSUE THREAD

**Issue by StevenJiang1110** [asterinas/asterinas#41]
- [x] use safeptr wrapper to deal with union safely(siginfo_t....)
- [x] sig_context can be removed
- [x] wait_until can provide more tiny interface(Result<Option<R>> -> Option<R>)
- [ ] enable wait interruptible in std
- [ ] determine the suitable lock granularity
