### ISSUE TITLE
Tracking issue for missing features in OSDK

### ISSUE THREAD

**Issue by StevenJiang1110** [asterinas/asterinas#661]
This issue is used to track missing features for OSDK that will be implemented in the future.

# Manifest: 
- [ ] Support multiple sets of QEMU parameters, corresponding to the current `select` syntax.
- [ ] Support per-crate's `OSDK.toml` when the crate is in a workspace.
# Commands:
### new
- [x] Use the correct dependency path when creating crates in Asterinas
### build & run
- [x] `build` and `run` should be able to run in workspace root.
- [x]  Support more Cargo options, like `--release` and `--features`
# Internal:
- [ ] OSDK should have a minimum supported version of Cargo. 
- [x] Update the integration test: use local `aster-frame`, instead of `aster-frame` from GitHub.

**Comment by StevenJiang1110** [comment]
Done
