### ISSUE TITLE
Implement the component initialization mechanism

### ISSUE THREAD

**Issue by sdww0** [asterinas/asterinas#67]
We want to implement a component system initialization method that makes it easy for component developers to register components with the component system. The component initialization mechanism should follow the following rules.

1. Components should be initialized in priority. A component may depend on the initialization of other components, so they need to wait for other components to initialize. We want to automatic generate priority and developers do not need to fill in the priority.
2. Component system can automatically find the component name and match the component name with priority at compile time or runtime.

## TODOs

- [x] Automatic generate priority.  
- [x] Match the component name with the priority.
- [x] Extract the component system as a separate crate
