### ISSUE TITLE
Tracking issues for improving the scheduling subsystem

### ISSUE THREAD

**Issue by tatetian** [asterinas/asterinas#775]
This issue tracks planned improvements for the scheduling subsystem of Asterinas.

- [ ] #723
- [ ] #774
- [ ] Schedule user programs preemptively
- [ ] Overhaul the scheduler API of the Framework
- [ ] Add the CFS scheduler

**Comment by jellllly420** [comment]
Claim #723 and #774.

**Comment by js2xxx** [comment]
Fix task 3 in #776

**Comment by skpupil** [comment]
Perhaps it's time to consider removing the `vmo` mechanism. It seems that this mechanism has poor performance and lacks clear advantages. If the scheduling system continues to rely on this mechanism, it may become difficult to change course in the future.  THX.

**Comment by tatetian** [comment]
> Perhaps it's time to consider removing the `vmo` mechanism.

We need a proposal for an alternative.

**Comment by junyang-zh** [comment]
> > Perhaps it's time to consider removing the `vmo` mechanism.
> 
> Agree, but we need a proposal for an alternative.

Behold, detailed designs documentation is on it's way!

**Comment by anbo225** [comment]
Claim #799 #800

**Comment by skpupil** [comment]
> > Perhaps it's time to consider removing the `vmo` mechanism.
> 
> Agree, but we need a proposal for an alternative.
> 
> > If the scheduling system continues to rely on this mechanism
> 
> Which part of the scheduling system relies on `Vmo`? You meant the bug filed by #746 ?

I recall someone told me that the development of our scheduling system was significantly hindered for a prolonged period by issue 632 related to vmo. I'm uncertain if similar impediments will arise in the future, particularly with the upcoming implementation of Shared Memory (SHM) if it is depends on vmo. What I can affirm is that, considering vmo's impending obsolescence, it's likely unwise for us to proceed with implementing further features relying on vmo at this stage.

**Comment by skpupil** [comment]
> > > Perhaps it's time to consider removing the `vmo` mechanism.
> > 
> > 
> > Agree, but we need a proposal for an alternative.
> 
> Behold, detailed designs documentation is on it's way!

Excellent！！！
