### ISSUE TITLE
Tracking issue for RISC-V support

### ISSUE THREAD

**Issue by YanWQ-monad** [asterinas/asterinas#777]
This issue is used to track the development of RISC-V architecture support.

### Proposed Steps

1. Refactor existing architecture-related code, so that new architecture could be easier to add (i.e. without modification to other architectures).
   - #802
   - #805
   - #808
   - #878
   - #879 
   - #880
   - #1070
   - #1071 
   - #1072 
   - #1087 
   - #1104
2. Add basic RISC-V support, including booting, memory management, and context switch, and successfully enter userspace in RISC-V.
   - #924 (RFC)
   - #1093 
3. Implement RISC-V external interrupts handling and related peripheral device drivers.
   - #1238 (introduce RISC-V CI)
   - #1695

### Prerequisite PRs
There are some pending changes in the framework, and current work is (or will be) based on them to minimize the workload.
- #704
- #713
- #707 (optional)

And some necessary changes in the dependencies.
- ~~asterinas/trapframe-rs#3~~

### Known Issues

> Can also be categorized as the next step of work.

- [x] kernel panic in `writev` when executing `busybox sh -l`.
      #770
- [ ] `SYS_ppoll` is not implemented (`SYS_poll` not exists on RISC-V).
- [x] [`getrandom`](https://github.com/rust-random/getrandom) crate is not available on baremetal RISC-V environment.
      #803

**Comment by anbo225** [comment]
Is there still someone tracking and completing this issue? If not, I can complete the tasks in the plan.  @YanWQ-monad @tatetian

**Comment by xuehaonan27** [comment]
I am going to track and complete this issue.

**Comment by lrh2000** [comment]
I think this tracking issue can be closed since there is nothing to track (all PRs have been merged or closed).

https://github.com/asterinas/asterinas/issues/2546 is perhaps more relevant now.
