### ISSUE TITLE
[Performance] Tracking issue for improving the performance of RamFs

### ISSUE THREAD

**Issue by liqinggd** [asterinas/asterinas#791]
1. Potential optimization areas for memory I/O are as follows:
- [x] Reading/writing data via PageCache(Vmo) https://github.com/asterinas/asterinas/pull/832
- [ ] Extra heap allocations and memory copies during Read/Write operations
- [x] Reading/writing data via Vmar
- [x] Page allocation and zeroing

2. Potential optimization areas for syscalls are as follows:
- [x] Activating page table https://github.com/asterinas/asterinas/pull/811
- [x] log_syscall_entry. https://github.com/asterinas/asterinas/pull/818
- [x] Handle pending signal/preempt/Multiple checks of Thread state https://github.com/asterinas/asterinas/pull/826
- [x] Trapframe #842

**Comment by liqinggd** [comment]
We performed a benchmark on sequential read scenarios in RamFS to verify the difference in performance relative to Linux and aimed to pinpoint the memory I/O bottlenecks. The specific overhead data pertaining to memory I/O are presented in the following figure:

Sequential read Buffer Size = 8K, with the data already residing in Page Cache.
![image](https://github.com/asterinas/asterinas/assets/49150782/92e33a37-5485-4edc-bef4-387f374b59af)

As can be seen, the primary performance bottleneck lies in the handle syscall portion. We further break down this information in the following figure:
![image](https://github.com/asterinas/asterinas/assets/49150782/a2906425-ee66-4a3e-ad37-2f5bfc949802)
In the graph, Direct Memcpy represents directly copying memory from kernel space to user space, which consumes approximately 780 CPU cycles. Thus, this value serves as the upper limit of our optimization target (i.e., directly copying memory from Page Cache into user memory).

The code：
https://github.com/asterinas/asterinas/blob/698e7481508712a477fd8f043fc25951051324a3/kernel/aster-nix/src/syscall/read.rs#L8
```rust
pub fn sys_read(fd: FileDescripter, user_buf_addr: Vaddr, buf_len: usize) -> Result<SyscallReturn> {
    // The log_syscall_entry macro consumes 400 CPU cycles
    log_syscall_entry!(SYS_READ);
    
    debug!(
        "fd = {}, user_buf_ptr = 0x{:x}, buf_len = 0x{:x}",
        fd, user_buf_addr, buf_len
    );
    let current = current!();
    let file_table = current.file_table().lock();
    let file = file_table.get_file(fd)?;
    
    // Additional heap allocation and initialization consume 360 CPU cycles.
    let mut read_buf = vec![0u8; buf_len];
    
    // Reading data from Page Cache consumes 3600 CPU cycles.
    let read_len = file.read(&mut read_buf)?;
    
    // Writing data into Vmar consumes 4600 CPU cycles.
    write_bytes_to_user(user_buf_addr, &read_buf)?;
    
    Ok(SyscallReturn::Return(read_len as _))
}
```

https://github.com/asterinas/asterinas/blob/698e7481508712a477fd8f043fc25951051324a3/kernel/aster-nix/src/vm/vmo/mod.rs#L337
```rust
pub fn read_bytes(&self, offset: usize, buf: &mut [u8]) -> Result<()> {
    let read_len = buf.len();
    let read_range = offset..(offset + read_len);
    
    // Committing Pages consumes 600 CPU cycles.
    let frames = self.commit(read_range, false)?;
    let read_offset = offset % PAGE_SIZE;
    
    // Entering the read_bytes within `VmFrameVec`. 
    // Potential optimization point: If `VmFrames` are contiguous in address,
    // a single copy operation should suffice.
    Ok(frames.read_bytes(read_offset, buf)?)
}
```

**Comment by liqinggd** [comment]
We further validated the overhead associated with syscall system calls themselves through benchmarking `getpid`. The experimental results are as follows:
![image](https://github.com/asterinas/asterinas/assets/49150782/7c58c52d-a824-4574-bdcd-7fb3ae7fcb4c)

The code:
https://github.com/asterinas/asterinas/blob/698e7481508712a477fd8f043fc25951051324a3/kernel/aster-nix/src/thread/task.rs#L16
```rust
loop {
    // This execute operation consumes 1555 CPU cycles.
    let user_event = user_mode.execute();
    let context = user_mode.context_mut();
    
    // Here, handle_user_event processes system calls, such as invoking sys_getpid.
    handle_user_event(user_event, context);
    
    // The following code snippet consumes 1430 CPU cycles.
    let current_thread = current_thread!();
    if current_thread.status().lock().is_exited() {
        break;
    }
    
    // Can handle_pending_signal return quickly?
    handle_pending_signal(context).unwrap();
    if current_thread.status().lock().is_exited() {
        debug!("exit due to signal");
        break;
    }
    while current_thread.status().lock().is_stopped() {
        Thread::yield_now();
        debug!("{} is suspended.", current_thread.tid());
        handle_pending_signal(context).unwrap();
    }
    
    // Can preempt return quickly?
    preempt();
}
```

https://github.com/asterinas/asterinas/blob/698e7481508712a477fd8f043fc25951051324a3/framework/aster-frame/src/user.rs#L140
```rust
pub fn execute(&mut self) -> UserEvent {
    // Activating the page table here consumes 255 CPU cycles.
    unsafe {
        self.user_space.vm_space().activate();
    }
    debug_assert!(Arc::ptr_eq(&self.current, &Task::current()));

    // Here, trapframe is invoked, consuming 1300 CPU cycles.
    self.context.execute()
}
```

**Comment by junyang-zh** [comment]
#713 enables faster VmIO for VmSpace for long buffers. We can bypass VmMappings in this case. And the later designs for process vm management may remove VmMappings for most cases.

```rust
impl VmIo for VmSpace {
    fn read_bytes(&self, vaddr: usize, buf: &mut [u8]) -> Result<()> {
        self.memory_set.lock().read_bytes(vaddr, buf)
        let range_end = vaddr.checked_add(buf.len()).ok_or(Error::Overflow)?;
        let vaddr = vaddr.align_down(PAGE_SIZE);
        let range_end = range_end.align_up(PAGE_SIZE);
        for qr in self.query_range(&(vaddr..range_end))? {
            if matches!(qr, VmQueryResult::NotMapped { .. }) {
                return Err(Error::AccessDenied);
            }
        }
        self.activate();
        buf.clone_from_slice(unsafe { core::slice::from_raw_parts(vaddr as *const u8, buf.len()) });
        Ok(())
    }

    fn write_bytes(&self, vaddr: usize, buf: &[u8]) -> Result<()> {
        self.memory_set.lock().write_bytes(vaddr, buf)
        let range_end = vaddr.checked_add(buf.len()).ok_or(Error::Overflow)?;
        let vaddr = vaddr.align_down(PAGE_SIZE);
        let range_end = range_end.align_up(PAGE_SIZE);
        for qr in self.query_range(&(vaddr..vaddr + range_end))? {
            match qr {
                VmQueryResult::NotMapped { .. } => return Err(Error::AccessDenied),
                VmQueryResult::Mapped { info, .. } => {
                    if !info.prop.perm.contains(VmPerm::W) {
                        return Err(Error::AccessDenied);
                    }
                }
            }
        }
        self.activate();
        unsafe { core::slice::from_raw_parts_mut(vaddr as *mut u8, buf.len()) }
            .clone_from_slice(buf);
        Ok(())
    }
}
```

**Comment by liqinggd** [comment]
#1057 tracks the unsolving issue.
