### ISSUE TITLE
Tracking issue for publishing OSDK

### ISSUE THREAD

**Issue by StevenJiang1110** [asterinas/asterinas#881]
This is the tracking issue for the things remaining to be done when we trying to officially publish OSDK.

Publishing OSDK involves publishing the aster-frame crate, along with some of its dependent crates (such as ktest), and the cargo-osdk tool. By doing so, we aim to align our development and release process more closely with community conventions.

This is not a full list. If anyone think there are more things to be none, we will add to the list.

- [x] Polish the OSDK ducumentation #869
- [x] Create a basic API documentation style guideline #882 
- [x] Polish the `aster-frame` documentation according to the style guideline #893 
- [x] Decide where to publish `aster-frame`
  - [x] ~Publish all dependent crates to crates.io, if we want to pubish aster-frame to crates.io~
  - [ ] If not, we should give each version release a git tag #913 
- [x] Publish the documentation of aster-frame #912 
- [ ] Maintain the changelog #917 
- [ ] Change(Add) the owner of all Asterinas crates in crates.io  as the Asterinas organization account
- [ ] (Maybe) maintain a FAQ page
- [ ] Announce OSDK

**Comment by StevenJiang1110** [comment]
About where to publish aster-frame:

We temporarily decide to host the documentation of aster-frame at a [self-hosted repo](asterinas.github.io/api-docs/aster-frame).

In the long term, we may still want to upload the documentation to crates.io, but this can only be done when the dependent crates of aster-frame are all published.

**Comment by StevenJiang1110** [comment]
Done
