### ISSUE TITLE
Tracking issue to support running Unixbench, IOzone, and LMbench

### ISSUE THREAD

**Issue by sdww0** [asterinas/asterinas#889]
I attempted to run the Unixbench, IOzone, and LMbench benchmarks on Asterinas, and it seems that Asterinas is still not fully capable of running all three benchmarks. After implementing some quick fixes (#774, #790, #785), only some of the Unixbench tests are functioning properly. Below are some of the results from Unixbench after making modifications to the preemptive scheduling.

| |pipe|spawn|context1|syscall|
|-|-|-|-|-|
|**Asterinas**|4931483|66197|1102244|4328029|
|**Linux**|28419638|116831|3403803|29433054|
|**Linux/Asterinas**| 5.76| 1.76| 3.09| 6.8|

I've summarized the issues that Asterinas still needs to address in order to support running these benchmarks:

- [x] #774 
- [x] #790 
- [ ] #785 
- [x] **This problem seems to only appear in my machine, so I mark it as resolved.** Potential bug in `exec` system calls: This bug arises from the failure of LMbench and Unixbench-execl, both of which use `exec` for testing. In LMbench, `exec` is used to create child processes for running the test program, and it triggers a page fault in Asterinas that forces LMbench to exit. In the case of Unixbench-execl, it continues running after a timeout and does not wake up properly."
- [x] Split BIO request: IOzone and Unixbench-fstime will read and write large blocks, requiring the VirtIO block device to separate these requests.[Panic location](https://github.com/asterinas/asterinas/blob/main/kernel/comps/virtio/src/device/block/device.rs#L360)

What's more, I found some points that would make the performance better:

- [ ] Redesign of preemptive scheduling: The current preemptive scheduling takes place after every syscall and can make Unixbench(syscall-related benchmark) less performant. I added an interval for preemptive scheduling in my testing, and I don't think it will fix the problem.
- [x] Trapframe refactoring: I tested the performance of the `trapframe` by directly returning in some syscalls after [`self.user_context.run()`](https://github.com/asterinas/asterinas/blob/main/framework/aster-frame/src/arch/x86/cpu.rs#L270). The results show that the `trapframe` itself is twice as slower as Linux.
- Remove some conversion: I'm unsure this will lead to a performance improvement. Although it did enhance performance in my tests after removing [`CpuException::to_cpu_exception`](https://github.com/asterinas/asterinas/blob/main/framework/aster-frame/src/arch/x86/cpu.rs#L270), it appeared to be unstable.

**Comment by liqinggd** [comment]
> Split BIO request: IOzone and Unixbench-fstime will read and write large blocks, requiring the VirtIO block device to separate these requests.[Panic location](https://github.com/asterinas/asterinas/blob/main/kernel/comps/virtio/src/device/block/device.rs#L360)

PR #909 can fix this issue

**Comment by skpupil** [comment]
I used the latest version of the test, but I found that the various test items did not work properly, first of all, the time is not accurate, if you specify 1 second, the actual time is longer. Then, the test results cannot be output to the command line. You have encountered these problems, you can try to test on the latest system, looking forward to your reply.

**Comment by sdww0** [comment]
> I used the latest version of the test, but I found that the various test items did not work properly, first of all, the time is not accurate, if you specify 1 second, the actual time is longer. Then, the test results cannot be output to the command line. Are you have encountered these problems, if you can try to test on the latest system, looking forward to your reply.

Yes, running 'Unixbench' or another benchmark requires fixing one more problem, as mentioned in PR #908.

**Comment by skpupil** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>


unixbench | linux | jinux | 占比 | cmd
-- | -- | -- | -- | --
fstime | # ./fstime -b 256 -m 1024 | ~ # ./fstime -b 256 -m 1024 |   | .
Write done: 3411968 in 2.0012, score 426231 | Write done: 1990656 in 2.0047, score 248247
COUNT\|426231\|0\|KBps | COUNT\|248247\|0\|KBps
TIME\|2.0 | TIME\|2.0
Read done: 4453315 in 2.0000, score 556661 | Read done: 1989297 in 2.0004, score 248616
COUNT\|556661\|0\|KBps | COUNT\|248616\|0\|KBps
TIME\|2.0 | TIME\|2.0
Copy done: 9842454 in 10.0000, score 246061 | Copy done: 4788220 in 10.0004, score 119700
COUNT\|246061\|0\|KBps | COUNT\|119700\|0\|KBps
TIME\|10.0 | TIME\|10.0
syscall | 7088893 | 4584922 | 64.68% | ./pgms/syscall 10 m



  | 16794674 | 11044217 | 65.76% | c
  | 36309966 | 24448082 | 67.33% | g
  | 28042 | 4279 | 15.26% | e


hanoi | 5566821 | 4902091 | 88.05% | 10
arithoh | 7814200114 | 7091244427 | 90.75% | time ./pgms/arithoh 10
spawn | 138792 | 4788 | 3.45% | time ./pgms/spawn 10
pipe | 11971637 | 4877153 | 40.74% | 10
dhry2 | 527629494 | 424445532 | 80.44% | 10
double | 348402264 | 306384375 | 87.94% | 10
dhry2reg | 516790735 | 432383981 | 83.67% | 10
long | 343677188 | 311917437 | 90.76% | 10
register | 350434304 | 311153795 | 88.79% | 10
short | 349710951 | 314213942 | 89.85% | 10
whetstone-double | 9474 | 8824 | 93.14% | 10



</body>

</html>

I'm using the linux kernel, not the ubuntu distribution. And both comparison tests specified kvm mode. 
```
qemu-system-x86_64 -kernel linux-6.0/arch/x86_64/boot/bzImage  -cpu Icelake-Server,+x2apic   --no-reboot  -smp 1 -m 8G  -hda rootfs.ext4 -append "root=/dev/sda rw console=ttyS0, 115200 acpi=off nokaslr" -serial stdio -display none --enable-kvm
```
