### ISSUE TITLE
Tracking issue for SMP support

### ISSUE THREAD

**Issue by junyang-zh** [asterinas/asterinas#999]
### Description

In this issue I will track the development process of the SMP (symmetric multiprocessing support) for Asterinas.

### Current Status

#707 will be taken over by @junyang-zh and separated in to atomic pull requests to facilitate integration. The topological order introducing full SMP support will be listed as follows.

Fixing or work around obvious problems and races:
- [x] VirtIO block device multi-queue (#1030 contains a workaround);
- [x] logging locks #1005 ;
- [ ] Implement a ring buffer for printing in kernel from `aster-nix` ;
- [x] More checks needed for handling an already-addressed page fault #1158 .

Bring SMP support:
- [x] Adding IPI #998 ;
- [x] Refactor `cpu_local!` #997 ;
- [x] Refactor exceptions #1004 ;
- [x] Fix `cpu_local!` and preempt count #1073 ;
- [x] Move data structures for CPU set and states #1030 ;
- [x] Support bootstrapping application processors (AP) #1030 ;
- [x] The new scheduler API #990 ;
- [x] Inter-processor call #1158 and #1206 ;
- [x] Support remote TLB shoot down #1140 and #1158 ;
- [x] Attach tasks to the APs #1219 ;
- [x] SMP tests #1219 ;

**Comment by junyang-zh** [comment]
I think that the SMP infrastructure in OSTD is working at the moment, in spite of a range of racing issues in the kernel. I am happily closing this tracking issue and we will track individual bugs with separate issues.
